game_logo = [r" ___________  ___  _____  _____  ______  ___  _____  _____ ",
             r"/  ___| ___ \/ _ \/  __ \|  ___| | ___ \/ _ \/  __ \|  ___|",
             r"\ `--.| |_/ / /_\ \ /  \/| |__   | |_/ / /_\ \ /  \/| |__  ",
             r" `--. \  __/|  _  | |    |  __|  |    /|  _  | |    |  __| ",
             r"/\__/ / |   | | | | \__/\| |___  | |\ \| | | | \__/\| |___ ",
             r"\____/\_|   \_| |_/\____/\____/  \_| \_\_| |_/\____/\____/ "
]

shop_logos = [
    [r" ______     __  __     ______     ______  ",
     r"/\  ___\   /\ \_\ \   /\  __ \   /\  == \ ",
     r"\ \___  \  \ \  __ \  \ \ \/\ \  \ \  _-/ ",
     r" \/\_____\  \ \_\ \_\  \ \_____\  \ \_\   ",
     r"  \/_____/   \/_/\/_/   \/_____/   \/_/   "],
    [r"  __      _   _               _ ___ ",
     r" (_  |_| / \ |_) __ /\ __ |  / \ |  ",
     r" __) | | \_/ |     /--\   |_ \_/ |  "],
    [r"oooo     oooo  o      ooooo        oooooooo8 ooooo ooooo  ooooooo  oooooooooo  ",
     r" 88   88  88  888      888        888         888   888 o888   888o 888    888 ",
     r"  88 888 88  8  88     888         888oooooo  888ooo888 888     888 888oooo88  ",
     r"   888 888  8oooo88    888      o         888 888   888 888o   o888 888        ",
     r"    8   8 o88o  o888o o888ooooo88 o88oooo888 o888o o888o  88ooo88  o888o       "],
    [r"   __            __                     ",
     r"  /  )          /  )                    ",
     r" /--<  o _,    /  /. . __.  _   __.  __ ",
     r"/___/_<_(_)_  (_\/(_/_(_/|_/_)_(_/|_/ (_",
     r"         /|      `                      ",
     r"        |/                              "],
    [r",     .            ,-.  .           ",
     r"|     |           (   ` |           ",
     r"| ;-. |-  ,-. ;-.  `-.  |-. ,-. ;-. ",
     r"| | | |   |-' |   .   ) | | | | | | ",
     r"' ' ' `-' `-' '    `-'  ' ' `-' |-' ",
     r"                                '   "],
    [r" ____ ____ ____ ____ ____ ____ ",
     r"||S |||a |||t |||u |||r |||n ||",
     r"||__|||__|||__|||__|||__|||__||",
     r"|/__\|/__\|/__\|/__\|/__\|/__\|"]
]

fuelstation_logos = [
    [r" _______  _______  _______  _______  _______    _______           _______  _        _       ",
     r"(  ____ \(  ____ )(  ___  )(  ____ \(  ____ \  (  ____ \|\     /|(  ____ \( \      ( \      ",
     r"| (    \/| (    )|| (   ) || (    \/| (    \/  | (    \/| )   ( || (    \/| (      | (      ",
     r"| (_____ | (____)|| (___) || |      | (__      | (_____ | (___) || (__    | |      | |      ",
     r"(_____  )|  _____)|  ___  || |      |  __)     (_____  )|  ___  ||  __)   | |      | |      ",
     r"      ) || (      | (   ) || |      | (              ) || (   ) || (      | |      | |      ",
     r"______) || )      | )   ( || (______| (______  ______) || )   ( || (______| (______| (______",
     r"\_______)|/       |/     \|(_______/(_______/  \_______)|/     \|(_______/(_______/(_______/"],
    [r" _____                _____                 _         ",
     r"|__   |___ ___ ___   |   __|___ ___ ___ ___|_|___ ___ ",
     r"|   __| -_|  _| . |  |   __|   | -_|  _| . | | -_|_ -|",
     r"|_____|___|_| |___|  |_____|_|_|___|_| |_  |_|___|___|",
     r"                                       |___|          "],
    [r"   _____                       ______                  ______                              ",
     r"  / ___/____  ____ _________  / ____/___              / ____/  ______  ________  __________",
     r"  \__ \/ __ \/ __ `/ ___/ _ \/ / __/ __ \   ______   / __/ | |/_/ __ \/ ___/ _ \/ ___/ ___/",
     r" ___/ / /_/ / /_/ / /__/  __/ /_/ / /_/ /  /_____/  / /____>  </ /_/ / /  /  __(__  |__  ) ",
     r"/____/ .___/\__,_/\___/\___/\____/\____/           /_____/_/|_/ .___/_/   \___/____/____/  ",
     r"    /_/                                                      /_/                           "],
    [r" ________                 ____    ____        __         _   __         ",
     r"|_   __  |               |_   \  /   _|      [  |       (_) [  |        ",
     r"  | |_ \_| _   __   .--.   |   \/   |   .--.  | |.--.   __   | | .---.  ",
     r"  |  _| _ [ \ [  ]/ .'`\ \ | |\  /| | / .'`\ \| '/'`\ \[  |  | |/ /__\\ ",
     r" _| |__/ | > '  < | \__. |_| |_\/_| |_| \__. ||  \__/ | | |  | || \__., ",
     r"|________|[__]`\_] '.__.'|_____||_____|'.__.'[__;.__.' [___][___]'.__.' "],
    [r"███████ ██    ██ ███████ ██      ███████  █████  ███████ ██    ██ ",
     r"██      ██    ██ ██      ██      ██      ██   ██ ██       ██  ██  ",
     r"█████   ██    ██ █████   ██      █████   ███████ ███████   ████   ",
     r"██      ██    ██ ██      ██      ██      ██   ██      ██    ██    ",
     r"██       ██████  ███████ ███████ ███████ ██   ██ ███████    ██    "]
]

intro_dialogue = ["Hello travellers, welcome to space race!",
                  "You found yourself crashed on a far away planet, and alien mafia are looking to find and capture you.",
                  "It’s time to embark on a journey on this mysterious planet filled with challenges and surprises\n          to find components that will help you build a new space craft, so you can safely get back home.",
                  "Collect all 7 components and fuel up your tank to escape the planet.",
                  "Oh, and one more thing… only one of you can escape.",
                  "Goodluck, travellers. May the best win!"
]

spaces_centers = ["Charlie, Hotel, India, Mike, Alpha, Echo, Romeo, Alpha - \"CHIMAERA\"",
                  "Charlie, India, November, Delta, Echo, Romeo - \"CINDER\"",
                  "Kilo November India Golf Hotel Tango Foxtrot Alpha Lima Lima - \"KNIGHTFALL\"",
                  "Victor Alpha Delta Echo Romeo - \"VADER\"",
                  "Lima Uniform November Alpha - \"LUNA\"",
                  "Sierra Oscar Lima India Sierra - \"SOLIS\"",
                  "Echo Lima Yankee Sierra India Uniform Mike - \"ELYSIUM\"",
                  "Victor Oscar Yankee Alpha Golf Echo Romeo - \"VOYAGER\"",
                  "Hotel Oscar Romeo India Zulu Oscar November - \"HORIZON\"",
                  "Hotel Alpha Romeo Victor Echo Sierra Tango Echo Romeo - \"HARVESTER\"",
                  "Whiskey Alpha Romeo - Mike Alpha November Tango Lima Echo - \"WAR-MANTLE\"",
                  "Yankee Oscar Uniform Romeo Mike Oscar Mike - \"YOURMOM\""
]

spaces_station = ["Alpha Romeo Echo Sierra - \"ARES\"",
                  "Hotel Echo Lima India Oscar Sierra - \"HELIOS\"",
                  "Hotel Alpha Delta Echo Sierra - \"HADES\"",
                  "Papa Oscar Sierra Echo India Delta Oscar November - \"POSEIDON\"",
                  "Zulu Echo Uniform Sierra - \"ZEUS\"",
                  "Mike India November Echo Romeo Victor Alpha - \"MINERVA\"",
                  "Alpha Papa Oscar Lima Lima Oscar - \"APOLLO\"",
                  "Alpha Papa Oscar Lima Lima Oscar 13 - \"APOLLO 13\"",
                  "Alpha Papa Oscar Lima Lima Oscar 13 - \"APOLLO 11\"",
                  "Victor Uniform Lima Charlie Alpha November - \"VULCAN\"",
                  "Charlie Echo Romeo Echo Sierra - \"CERES\"",
                  "Oscar Sierra India Romeo India Sierra - \"OSIRIS\"",
                  "Alpha November Uniform Bravo India Sierra - \"ANUBIS\"",
                  "Echo Lima India Zulu Alpha Bravo Echo Tango Hotel II - \"Elizabeth II\"",
                  "Golf Oscar Delta - \"GOD\"",
                  "Delta Echo Alpha Tango Hotel   Sierra Tango Alpha Romeo Tango - \"DEATH STAR\"",
                  "Delta Echo Alpha Tango Hotel   Sierra Tango Alpha Romeo Tango II - \"DEATH STAR II\"",
                  "Tango Alpha November Tango India Sierra Sierra - \"TANTISS\""
                  "Delta Alpha Romeo Oscar - \"DARO\""
]

shop_keepers = [
    ["Oddly Kind Alien",
     "Oddly Kind Alien",
     ["Greeting, friend!",
      "I am here to assist you on your cosmic journey",
      "Looking to trade or acquire cosmic treasures?",
      "Feel free to peruse my collection, buy, sell continue your adventure through the stars whenever you're ready"]],
    ["Dr. Quasar, The Galactic Inventor",
     "Dr. Quasar",
     ["Greetings, Cosmic traveler!",
      "I am Dr. Quasar, Inventor extraordinair and seeker of the Unknown",
      "Seeking something to tinker with or looking to offload some space debris?",
      "Explore my workshop, buy, sell or Continue your cosmic expedition at your leisure"]],
    ["Mystic Moonsong, The Cosmic Seer",
     "Mystic Moonsong",
     ["Ah, greetings, wanderer of the stars",
      "I am Mystic Moonsong, keeper of the cosmic mysteries and guide to the celestial realms",
      "Seeking enlightenment or seeking to trade?",
      "Peer into the depths of my emporium, buy, sell, or depart on your cosmic quest when the stars align"]],
    ["Zorgon, the Galactic Mechanic",
     "Zorgon",
     ["Greeting, weary traveller!",
      "I am Zorgon, the master of machines and keeper of cosmic contraptions",
      "Need a spare part or seeking to trade?",
      "You've come to the right place",
      "Browse my inventory, buy, sell or depart on your interstellar journey"]],
    ["Nebula Nova, The Cosmic Entrepeneur",
     "Nebula Nova",
     ["Salutations, fellow cosmic voyager!",
      "I am Nebula Nova, surveyor of all things celestial",
      "Looking to bargain or hoping to expand your cosmic collection?",
      "Explore my emporium, buy, sell or soar off into the endless expanse of space when you're ready",]],
    ["Orion Starlight, The Celestial Scholar",
     "Orion Starlight",
     ["Ah greetings, traveller of the stars",
      "I am Orion Starlight, keeper of the cosmic archives and guardian of ancient knowledge",
      "Seeking enlightenment or seeking to trade?",
      "Delve into the depths of my collection, buy, sell or continue your cosmic odyssey at your leisure"]]
]

rocket_parts = ["HEATSHIELD", "AVIONICS", "CONTROL SYSTEMS", "FUEL TANK", "ENGINES", "FUSELAGE", "COMMUNICATION SYSTEM"]